local hash = require "tpf2_mp/hash"

local M = { STABLE_TICKS = 12 }

local function empty(value)
  return type(value) == "table" and next(value) == nil
end

-- A failed typed replay may use buildConstruction only when the construction
-- is wholly self-contained. In that shape the resource, params, transform and
-- mod inventory are already content-attested, while its internal airport or
-- terminal graph is generated by the engine rather than carried in the wire
-- transaction. Never extend this escape hatch to a graph touching live world
-- inputs: those require the captured exact replay path.
function M.eligible(record, codec)
  local transaction = type(record) == "table" and record.transaction or nil
  local construction = transaction and type(transaction.constructions) == "table"
    and transaction.constructions[1] or nil
  local objects = transaction and transaction.edgeObjects or nil
  return record and record.replayPath == "helper-fallback"
    and transaction and codec.isConstructionSchema(transaction.schemaVersion)
    and construction and construction.mode == "build"
    and construction.kind ~= "asset"
    and #(construction.collateral or {}) == 0
    and #(record.localInputs or {}) == 0
    and #(transaction.nodes or {}) == 0 and #(transaction.edges or {}) == 0
    and empty(transaction.remove and transaction.remove.nodes or {})
    and empty(transaction.remove and transaction.remove.edges or {})
    and empty(objects and objects.add or {}) and empty(objects and objects.remove or {})
    and empty(objects and objects.retain or {})
end

function M.deltaReady(counts, removedCounts)
  -- An isolated build may remove nothing. Airports legitimately generate
  -- runway edge-object components; those are attested below with the graph.
  for kind, count in pairs(removedCounts or {}) do
    if kind ~= "asset" and count ~= 0 then return false, kind end
  end
  return true
end

function M.removedAssetsSafe(ids, deps)
  for _, localId in ipairs(ids or {}) do
    local key = tostring(localId)
    if deps.resolveCanonical(localId) or deps.logicalOwners[key]
      or deps.pinnedCustody[key] then
      return nil, "generated construction removed a managed asset"
    end
  end
  return true
end

local function fingerprintList(ids, kind, fingerprint)
  local result = {}
  for _, localId in ipairs(ids or {}) do
    local ok, value = pcall(fingerprint, localId, kind)
    if not ok or type(value) ~= "string" or value == "" then
      return nil, "generated " .. kind .. " fingerprint is unavailable"
    end
    result[#result + 1] = value
  end
  table.sort(result)
  return result
end

function M.attest(nodeIds, edgeIds, edgeObjectIds, removedAssetIds, deps)
  local nodes, nodeError = fingerprintList(nodeIds, "node", deps.fingerprint)
  if not nodes then return nil, nodeError end
  local edges, edgeError = fingerprintList(edgeIds, "edge", deps.fingerprint)
  if not edges then return nil, edgeError end
  local edgeObjects, objectError = fingerprintList(
    edgeObjectIds, "edge_object", deps.fingerprint)
  if not edgeObjects then return nil, objectError end
  local inspected, byId = deps.inspectEdges(edgeIds), {}
  for _, row in ipairs(inspected or {}) do byId[tonumber(row.localId)] = row end
  local carriers = {}
  for _, localId in ipairs(edgeIds or {}) do
    local row = byId[tonumber(localId)]
    if not row then return nil, "generated edge inspection is incomplete" end
    local categories = {}
    for _, object in ipairs(row.objects or {}) do
      categories[#categories + 1] = tonumber(object.category) or -1
    end
    table.sort(categories)
    local fingerprintOk, geometry = pcall(deps.fingerprint, localId, "edge")
    if not fingerprintOk then return nil, "generated edge fingerprint is unavailable" end
    carriers[#carriers + 1] = hash.value({
      geometry = geometry,
      carrier = tostring(row.carrier or "unknown"),
      resourceIndex = tonumber(row.resourceIndex) or -1,
      catenary = row.catenary == true,
      bus = row.bus == true,
      tramTrackType = tonumber(row.tramTrackType) or 0,
      objectCategories = categories,
    })
  end
  table.sort(carriers)
  return {
    schemaVersion = 1, nodeCount = #nodes, edgeCount = #edges,
    edgeObjectCount = #edgeObjects, removedSceneryCount = #(removedAssetIds or {}),
    digest = hash.value({ nodes = nodes, edges = edges,
      edgeObjects = edgeObjects, carriers = carriers }),
  }
end

function M.attestState(nodeIds, edgeIds, edgeObjectIds, removedAssetIds,
    state, canonical, world, inspectEdges)
  local safe, safeError = M.removedAssetsSafe(removedAssetIds, {
    resolveCanonical = function(localId)
      return canonical.resolveCanonical(state.canonical, "asset", localId)
    end,
    logicalOwners = state.world.logicalOwners,
    pinnedCustody = state.world.pinnedCustody,
  })
  if not safe then return nil, safeError end
  return M.attest(nodeIds, edgeIds, edgeObjectIds, removedAssetIds, {
    fingerprint = world.fingerprint, inspectEdges = inspectEdges,
  })
end

-- Helper-built airports and other self-contained constructions generate their
-- internal graph after the signed construction action has been decoded. Bind
-- that complete graph at the same authored finalisation boundary as the root.
-- Otherwise the next structural probe discovers the player-owned runway as
-- pre-existing topology and silently changes the canonical digest between
-- journalled events. Duplicate fingerprints are safe here: the attestation
-- proves the complete multiset and these auxiliary children are not direct UI
-- targets, so their peer-local tie order cannot affect the portable view.
function M.bindOutputs(record, nodes, edges, edgeObjects, deps)
  local bound = {}
  for _, descriptor in ipairs({
    { kind = "node", values = nodes },
    { kind = "edge", values = edges },
    { kind = "edge_object", values = edgeObjects },
  }) do
    local rows = {}
    for _, localId in ipairs(descriptor.values or {}) do
      if deps.resolveCanonical(descriptor.kind, localId) then
        return nil, "generated " .. descriptor.kind .. " was bound before finalisation"
      end
      local ok, fingerprint = pcall(deps.fingerprint, localId, descriptor.kind)
      if not ok or type(fingerprint) ~= "string" or fingerprint == "" then
        return nil, "generated " .. descriptor.kind .. " fingerprint is unavailable"
      end
      rows[#rows + 1] = { localId = localId, fingerprint = fingerprint }
    end
    table.sort(rows, function(a, b)
      if a.fingerprint ~= b.fingerprint then return a.fingerprint < b.fingerprint end
      return tonumber(a.localId) < tonumber(b.localId)
    end)
    for index, row in ipairs(rows) do
      local slot = descriptor.kind .. ":generated:" .. tostring(index)
      local cid = deps.createdId(descriptor.kind, record.eventId, index)
      local ok, bindError = deps.bind(cid, descriptor.kind, row.localId, {
        owner = record.companyCid, private = true,
        auxiliary = "generated-construction-topology",
        proposalDigest = record.transaction.digest, outputSlot = slot,
        fingerprint = row.fingerprint,
        topologyFingerprint = deps.topologyFingerprint
          and deps.topologyFingerprint(row.localId, descriptor.kind) or nil,
        topologyNeighbourFingerprint = deps.topologyNeighbourFingerprint
          and deps.topologyNeighbourFingerprint(row.localId, descriptor.kind) or nil,
      })
      if not ok then return nil, bindError end
      local key = tostring(row.localId)
      deps.logicalOwners[key] = record.companyCid
      deps.pinnedCustody[key] = {
        cid = cid, kind = descriptor.kind,
        logicalOwnerCid = record.companyCid,
        nativePlayerId = deps.ownerOf(row.localId) or record.nativeOwnerPlayerId,
        requestedPlayerId = deps.requestedPlayerId,
        reason = "canonical-generated-construction-topology",
      }
      bound[#bound + 1] = {
        kind = descriptor.kind, cid = cid, localId = row.localId, slot = slot,
      }
    end
  end
  return bound
end

function M.bindState(record, nodes, edges, edgeObjects, state, canonical, world)
  return M.bindOutputs(record, nodes, edges, edgeObjects, {
    fingerprint = world.fingerprint, ownerOf = world.ownerOf,
    topologyFingerprint = function(localId, kind)
      return world.topologyFingerprint(localId, kind, {
        registry = state.canonical, worldState = state.world,
        ownerCid = record.companyCid,
      })
    end,
    topologyNeighbourFingerprint = function(localId, kind)
      return world.topologyNeighbourFingerprint(localId, kind, {
        registry = state.canonical, worldState = state.world,
        ownerCid = record.companyCid,
      })
    end,
    resolveCanonical = function(kind, localId)
      return canonical.resolveCanonical(state.canonical, kind, localId)
    end,
    createdId = canonical.createdId,
    bind = function(cid, kind, localId, metadata)
      return canonical.bind(state.canonical, cid, kind, localId, metadata)
    end,
    logicalOwners = state.world.logicalOwners,
    pinnedCustody = state.world.pinnedCustody,
    requestedPlayerId = state.companies[record.companyCid].playerId,
  })
end

return M
