-- Generated by tools/generate_command_safety_registry.py; do not edit.
local policies = {
  [0] = { tag = 0, name = "SetGameSpeed", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "network_clock_runtime.set", ownership = "session-clock", cost = "none", postconditions = { "native-speed-equals-effective-speed", "all-peer-clock-generation" } },
  [1] = { tag = 1, name = "SetCalendarSpeed", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "calendar_runtime.set", ownership = "host-calendar", cost = "none", postconditions = { "all-peer-calendar-speed" } },
  [2] = { tag = 2, name = "UpdateLogo", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "unsupported", ownership = "company-owner", cost = "none", postconditions = { "logo-resource-equal" } },
  [3] = { tag = 3, name = "CreateLine", capturePoint = "visitor-after-local-apply", visitorHook = true, suppressionSafe = false, optimisticPassThrough = true, uiResult = "entity-callback", replay = "operation.line.create", ownership = "active-company", cost = "none", postconditions = { "line-exists", "line-owner-equal", "stops-equal" } },
  [4] = { tag = 4, name = "DeleteLine", capturePoint = "visitor-after-local-apply", visitorHook = true, suppressionSafe = false, optimisticPassThrough = true, uiResult = "callback", replay = "operation.line.delete", ownership = "line-owner", cost = "none", postconditions = { "line-absent", "dependent-services-retired" } },
  [5] = { tag = 5, name = "UpdateLine", capturePoint = "visitor-after-local-apply", visitorHook = true, suppressionSafe = false, optimisticPassThrough = true, uiResult = "callback", replay = "operation.line.update", ownership = "line-owner", cost = "none", postconditions = { "stops-equal", "terminal-alternatives-equal" } },
  [6] = { tag = 6, name = "SetLine", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "operation.vehicle.assign", ownership = "vehicle-and-line-owner", cost = "none", postconditions = { "vehicle-line-equal", "line-registration-equal" } },
  [7] = { tag = 7, name = "Reverse", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "operation.vehicle.reverse", ownership = "vehicle-owner", cost = "none", postconditions = { "vehicle-direction-equal" } },
  [8] = { tag = 8, name = "SetUserStopped", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "operation.vehicle.stop", ownership = "vehicle-owner-or-sync-barrier", cost = "none", postconditions = { "user-stopped-equal-except-barrier-hold" } },
  [9] = { tag = 9, name = "SetVehicleTargetMaintenanceState", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "operation.vehicle.maintenance", ownership = "vehicle-owner", cost = "authored-vehicle-economy", postconditions = { "maintenance-target-equal" } },
  [10] = { tag = 10, name = "SetVehicleShouldDepart", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "vehicle_sync_runtime.release", ownership = "sync-barrier", cost = "none", postconditions = { "station-round-release-equal" } },
  [11] = { tag = 11, name = "SendToDepot", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "operation.vehicle.send_to_depot", ownership = "vehicle-owner", cost = "authored-vehicle-economy", postconditions = { "depot-target-equal", "sell-on-arrival-equal" } },
  [12] = { tag = 12, name = "SellVehicle", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "operation.vehicle.sell_batch", ownership = "every-vehicle-owner", cost = "authoritative-resale", postconditions = { "vehicles-absent", "balance-delta-equal" } },
  [13] = { tag = 13, name = "BuyVehicle", capturePoint = "visitor-plus-stock-gui", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "entity-callback", replay = "operation.vehicle.buy", ownership = "depot-owner", cost = "authoritative-purchase", postconditions = { "vehicle-exists", "consist-equal", "owner-equal", "balance-delta-equal" } },
  [14] = { tag = 14, name = "ReplaceVehicle", capturePoint = "visitor-plus-stock-gui", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "entity-callback", replay = "operation.vehicle.replace", ownership = "vehicle-owner", cost = "authoritative-purchase-and-resale", postconditions = { "consist-equal", "owner-equal", "balance-delta-equal" } },
  [15] = { tag = 15, name = "BuildProposal", capturePoint = "make_cmd::BuildProposal+CommandList::Add+visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "proposal-callback", replay = "proposal_runtime.apply", ownership = "proposal-access-policy", cost = "authoritative-quoted-cost", postconditions = { "geometry-fingerprint-equal", "construction-fingerprint-equal", "ownership-equal", "balance-delta-equal" } },
  [16] = { tag = 16, name = "RemoveField", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "unsupported", ownership = "host-autonomy", cost = "none", postconditions = { "field-absence-equal" } },
  [17] = { tag = 17, name = "CreateTowns", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "entity-callback", replay = "unsupported", ownership = "host-world-authority", cost = "none", postconditions = { "town-set-equal" } },
  [18] = { tag = 18, name = "RemoveTown", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "unsupported", ownership = "host-world-authority", cost = "none", postconditions = { "town-absent" } },
  [19] = { tag = 19, name = "DevelopTown", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "town_development_runtime.apply", ownership = "host-town-model", cost = "none", postconditions = { "town-capacities-equal", "structural-fingerprint-equal" } },
  [20] = { tag = 20, name = "SetTownInfo", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "town_development_runtime.set_info", ownership = "host-town-model", cost = "none", postconditions = { "town-info-equal" } },
  [21] = { tag = 21, name = "InstantlyUpdateTownCargoNeeds", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "unsupported", ownership = "host-town-model", cost = "none", postconditions = { "town-cargo-needs-equal" } },
  [22] = { tag = 22, name = "ConnectTownsAndIndustries", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "unsupported", ownership = "host-world-authority", cost = "none", postconditions = { "connection-graph-equal" } },
  [23] = { tag = 23, name = "SetSimBuildingManualDevelopment", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "agent_policy_runtime.apply", ownership = "host-agent-policy", cost = "none", postconditions = { "manual-development-flag-equal" } },
  [24] = { tag = 24, name = "SetSimBuildingClosureTimeStamp", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "unsupported", ownership = "host-agent-policy", cost = "none", postconditions = { "closure-timestamp-equal" } },
  [25] = { tag = 25, name = "ReplaceTerrain", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "unsupported", ownership = "proposal-access-policy", cost = "authoritative-quoted-cost", postconditions = { "terrain-fingerprint-equal", "balance-delta-equal" } },
  [26] = { tag = 26, name = "SetDate", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "calendar_runtime.set_date", ownership = "host-calendar", cost = "none", postconditions = { "date-equal", "vehicle-availability-equal" } },
  [27] = { tag = 27, name = "SaveGame", capturePoint = "command-list-observer", visitorHook = false, suppressionSafe = false, optimisticPassThrough = false, uiResult = "callback", replay = "recovery.anchor_save", ownership = "local-recovery-only", cost = "none", postconditions = { "boundary-receipt-bound" } },
  [28] = { tag = 28, name = "SetColor", capturePoint = "visitor-after-local-apply", visitorHook = true, suppressionSafe = false, optimisticPassThrough = true, uiResult = "callback", replay = "operation.entity.color", ownership = "entity-owner", cost = "none", postconditions = { "color-equal" } },
  [29] = { tag = 29, name = "SetName", capturePoint = "visitor-after-local-apply", visitorHook = true, suppressionSafe = false, optimisticPassThrough = true, uiResult = "callback", replay = "operation.entity.name", ownership = "entity-owner", cost = "none", postconditions = { "name-equal" } },
  [30] = { tag = 30, name = "SetVehicleManualDeparture", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "callback", replay = "operation.vehicle.manual_departure", ownership = "vehicle-owner", cost = "none", postconditions = { "manual-departure-equal" } },
  [31] = { tag = 31, name = "Book", capturePoint = "command-list-observer", visitorHook = false, suppressionSafe = false, optimisticPassThrough = false, uiResult = "none", replay = "authored_finance_runtime.neutralize", ownership = "authoritative-economy", cost = "native-ledger-neutralized", postconditions = { "authored-balance-equal" } },
  [32] = { tag = 32, name = "SendScriptEvent", capturePoint = "native-send-command-wrapper", visitorHook = false, suppressionSafe = false, optimisticPassThrough = false, uiResult = "script-result", replay = "protocol.action_dispatch", ownership = "protocol-handler", cost = "action-defined", postconditions = { "canonical-digest-equal" } },
  [33] = { tag = 33, name = "SetNoCosts", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "unsupported", ownership = "match-configuration", cost = "none", postconditions = { "no-costs-flag-equal" } },
  [34] = { tag = 34, name = "SetAnimalState", capturePoint = "command-list-observer", visitorHook = false, suppressionSafe = false, optimisticPassThrough = false, uiResult = "none", replay = "cosmetic-autonomy", ownership = "native-cosmetic", cost = "none", postconditions = {  } },
  [35] = { tag = 35, name = "SpawnAnimal", capturePoint = "command-list-observer", visitorHook = false, suppressionSafe = false, optimisticPassThrough = false, uiResult = "entity-callback", replay = "cosmetic-autonomy", ownership = "native-cosmetic", cost = "none", postconditions = {  } },
  [36] = { tag = 36, name = "Debug_SetSimPersonState", capturePoint = "visitor", visitorHook = true, suppressionSafe = true, optimisticPassThrough = false, uiResult = "none", replay = "agent_presentation_runtime.apply", ownership = "host-agent-policy", cost = "none", postconditions = { "presented-agent-state-bounded" } },
}

local M = { SCHEMA_VERSION = 1, policies = policies }

function M.forTag(tag)
  tag = tonumber(tag)
  if not tag or tag ~= math.floor(tag) then return nil end
  return policies[tag]
end

function M.assertComplete()
  for tag = 0, 36 do
    local policy = policies[tag]
    assert(type(policy) == "table" and policy.tag == tag,
      "missing native command safety policy for tag " .. tostring(tag))
    assert(type(policy.capturePoint) == "string" and policy.capturePoint ~= "",
      "native command safety capture point is missing for tag " .. tostring(tag))
    assert(type(policy.replay) == "string" and policy.replay ~= "",
      "native command replay policy is missing for tag " .. tostring(tag))
    assert(type(policy.ownership) == "string" and policy.ownership ~= ""
        and type(policy.cost) == "string" and policy.cost ~= "",
      "native command authority policy is incomplete for tag " .. tostring(tag))
    assert(type(policy.postconditions) == "table"
        and (tag == 34 or tag == 35 or #policy.postconditions > 0),
      "native command postconditions are missing for tag " .. tostring(tag))
  end
  return true
end

return M
