local M = {
  LEGACY_SCHEMA_VERSION = 5,
  SCHEMA_VERSION = 6,
  LEGACY_CONSTRUCTION_SCHEMA_VERSION = 7,
  CONSTRUCTION_SCHEMA_VERSION = 8,
  NAMED_CONSTRUCTION_SCHEMA_VERSION = 9,
  MAX_NODES = 256,
  MAX_EDGES = 256,
  MAX_EDGE_OBJECTS = 256,
  MAX_CONSTRUCTION_NODES = 1024,
  MAX_CONSTRUCTION_EDGES = 1024,
  MAX_REMOVALS = 512,
  MAX_CONSTRUCTIONS = 1,
  MAX_CONSTRUCTION_COLLATERAL = 64,
  MAX_CONSTRUCTION_PARAM_VALUES = 8192,
  MAX_CONSTRUCTION_PARAM_DEPTH = 16,
  TRAM_TRACK_NONE = 0,
  TRAM_TRACK_PLAIN = 1,
  TRAM_TRACK_ELECTRIC = 2,
}

function M.isConstructionSchema(version)
  return version == M.CONSTRUCTION_SCHEMA_VERSION
    or version == M.NAMED_CONSTRUCTION_SCHEMA_VERSION
    or version == M.LEGACY_CONSTRUCTION_SCHEMA_VERSION
end

function M.hasStreetFeatures(version)
  return version == M.SCHEMA_VERSION or version == M.CONSTRUCTION_SCHEMA_VERSION
    or version == M.NAMED_CONSTRUCTION_SCHEMA_VERSION
end

return M
