#!/usr/bin/env python3
"""Generate native/Lua command policy views from the one safety registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "content" / "native-command-safety-v1.json"
CPP = ROOT / "native" / "include" / "tpf2mp" / "native_command_safety.generated.hpp"
LUA = ROOT / "tpf2_mp_1" / "res" / "scripts" / "tpf2_mp" / "native_command_safety_registry.lua"

REQUIRED = {
    "tag", "name", "capturePoint", "visitorHook", "suppressionSafe",
    "optimisticPassThrough", "uiResult", "replay", "ownership", "cost",
    "postconditions",
}
UI_RESULTS = {
    "none", "callback", "entity-callback", "proposal-callback",
    "script-result",
}


def load() -> dict:
    value = json.loads(SOURCE.read_text(encoding="utf-8"))
    if value.get("schemaVersion") != 1 or not isinstance(value.get("commands"), list):
        raise ValueError("command safety registry must use schema 1")
    commands = value["commands"]
    if len(commands) != 37:
        raise ValueError("command safety registry must describe all 37 native tags")
    for tag, command in enumerate(commands):
        if set(command) != REQUIRED or command["tag"] != tag:
            raise ValueError(f"command policy {tag} has missing/extra fields or wrong tag")
        text_fields = ("name", "capturePoint", "uiResult", "replay", "ownership", "cost")
        bool_fields = ("visitorHook", "suppressionSafe", "optimisticPassThrough")
        if any(not isinstance(command[field], str) or not command[field] for field in text_fields):
            raise ValueError(f"command policy {tag} has an empty text field")
        if any(type(command[field]) is not bool for field in bool_fields):
            raise ValueError(f"command policy {tag} has a non-boolean gate field")
        if command["uiResult"] not in UI_RESULTS:
            raise ValueError(f"command policy {tag} has an unknown UI-result contract")
        if not isinstance(command["postconditions"], list) or any(
            not isinstance(item, str) or not item for item in command["postconditions"]
        ):
            raise ValueError(f"command policy {tag} is malformed")
        if tag not in (34, 35) and not command["postconditions"]:
            raise ValueError(f"consequential command policy {tag} has no postcondition")
        if command["optimisticPassThrough"] and command["suppressionSafe"]:
            raise ValueError(f"command policy {tag} cannot be both suppressible and pass-through")
        if command["visitorHook"] and not (
            command["suppressionSafe"] or command["optimisticPassThrough"]
        ):
            raise ValueError(f"hooked command policy {tag} has no safe visitor behavior")
    return value


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_cpp(value: dict) -> str:
    rows = []
    for item in value["commands"]:
        postconditions = ",".join(item["postconditions"])
        rows.append(
            "    {" + ", ".join([
                str(item["tag"]), cpp_string(item["name"]),
                cpp_string(item["capturePoint"]),
                "true" if item["visitorHook"] else "false",
                "true" if item["suppressionSafe"] else "false",
                "true" if item["optimisticPassThrough"] else "false",
                cpp_string(item["uiResult"]), cpp_string(item["replay"]),
                cpp_string(item["ownership"]), cpp_string(item["cost"]),
                cpp_string(postconditions),
            ]) + "},"
        )
    return """// Generated by tools/generate_command_safety_registry.py; do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace tpf2mp::native_command {

struct CommandSafetyPolicy {
  std::size_t tag;
  std::string_view name;
  std::string_view capture_point;
  bool visitor_hook;
  bool suppression_safe;
  bool optimistic_pass_through;
  std::string_view ui_result;
  std::string_view replay;
  std::string_view ownership;
  std::string_view cost;
  std::string_view postconditions;
};

inline constexpr std::array<CommandSafetyPolicy, 37> kCommandSafetyRegistry{{
""" + "\n".join(rows) + """
}};

template <std::size_t Tag>
inline constexpr const CommandSafetyPolicy& CommandSafetyPolicyFor() {
  static_assert(Tag < kCommandSafetyRegistry.size());
  static_assert(kCommandSafetyRegistry[Tag].tag == Tag);
  return kCommandSafetyRegistry[Tag];
}

}  // namespace tpf2mp::native_command
"""


def lua_value(value: object, indent: int = 0) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "nil"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    if isinstance(value, list):
        return "{ " + ", ".join(lua_value(item, indent + 1) for item in value) + " }"
    raise TypeError(type(value))


def render_lua(value: dict) -> str:
    rows = []
    for item in value["commands"]:
        fields = []
        for key in [
            "tag", "name", "capturePoint", "visitorHook", "suppressionSafe",
            "optimisticPassThrough", "uiResult", "replay", "ownership", "cost",
            "postconditions",
        ]:
            fields.append(f"{key} = {lua_value(item[key])}")
        rows.append(f"  [{item['tag']}] = {{ " + ", ".join(fields) + " },")
    return """-- Generated by tools/generate_command_safety_registry.py; do not edit.
local policies = {
""" + "\n".join(rows) + """
}

local M = { SCHEMA_VERSION = 1, policies = policies }

function M.forTag(tag)
  tag = tonumber(tag)
  if not tag or tag ~= math.floor(tag) then return nil end
  return policies[tag]
end

function M.assertComplete()
  for tag = 0, 36 do
    local policy = policies[tag]
    assert(type(policy) == "table" and policy.tag == tag,
      "missing native command safety policy for tag " .. tostring(tag))
    assert(type(policy.capturePoint) == "string" and policy.capturePoint ~= "",
      "native command safety capture point is missing for tag " .. tostring(tag))
    assert(type(policy.replay) == "string" and policy.replay ~= "",
      "native command replay policy is missing for tag " .. tostring(tag))
    assert(type(policy.ownership) == "string" and policy.ownership ~= ""
        and type(policy.cost) == "string" and policy.cost ~= "",
      "native command authority policy is incomplete for tag " .. tostring(tag))
    assert(type(policy.postconditions) == "table"
        and (tag == 34 or tag == 35 or #policy.postconditions > 0),
      "native command postconditions are missing for tag " .. tostring(tag))
  end
  return true
end

return M
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    value = load()
    outputs = {CPP: render_cpp(value), LUA: render_lua(value)}
    failures = []
    for path, expected in outputs.items():
        if args.check:
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                failures.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    if failures:
        print("stale generated command safety registry: " + ", ".join(failures), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
