// Generated by tools/generate_command_safety_registry.py; do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace tpf2mp::native_command {

struct CommandSafetyPolicy {
  std::size_t tag;
  std::string_view name;
  std::string_view capture_point;
  bool visitor_hook;
  bool suppression_safe;
  bool optimistic_pass_through;
  std::string_view ui_result;
  std::string_view replay;
  std::string_view ownership;
  std::string_view cost;
  std::string_view postconditions;
};

inline constexpr std::array<CommandSafetyPolicy, 37> kCommandSafetyRegistry{{
    {0, "SetGameSpeed", "visitor", true, true, false, "none", "network_clock_runtime.set", "session-clock", "none", "native-speed-equals-effective-speed,all-peer-clock-generation"},
    {1, "SetCalendarSpeed", "visitor", true, true, false, "none", "calendar_runtime.set", "host-calendar", "none", "all-peer-calendar-speed"},
    {2, "UpdateLogo", "visitor", true, true, false, "callback", "unsupported", "company-owner", "none", "logo-resource-equal"},
    {3, "CreateLine", "visitor-after-local-apply", true, false, true, "entity-callback", "operation.line.create", "active-company", "none", "line-exists,line-owner-equal,stops-equal"},
    {4, "DeleteLine", "visitor-after-local-apply", true, false, true, "callback", "operation.line.delete", "line-owner", "none", "line-absent,dependent-services-retired"},
    {5, "UpdateLine", "visitor-after-local-apply", true, false, true, "callback", "operation.line.update", "line-owner", "none", "stops-equal,terminal-alternatives-equal"},
    {6, "SetLine", "visitor", true, true, false, "callback", "operation.vehicle.assign", "vehicle-and-line-owner", "none", "vehicle-line-equal,line-registration-equal"},
    {7, "Reverse", "visitor", true, true, false, "callback", "operation.vehicle.reverse", "vehicle-owner", "none", "vehicle-direction-equal"},
    {8, "SetUserStopped", "visitor", true, true, false, "callback", "operation.vehicle.stop", "vehicle-owner-or-sync-barrier", "none", "user-stopped-equal-except-barrier-hold"},
    {9, "SetVehicleTargetMaintenanceState", "visitor", true, true, false, "callback", "operation.vehicle.maintenance", "vehicle-owner", "authored-vehicle-economy", "maintenance-target-equal"},
    {10, "SetVehicleShouldDepart", "visitor", true, true, false, "none", "vehicle_sync_runtime.release", "sync-barrier", "none", "station-round-release-equal"},
    {11, "SendToDepot", "visitor", true, true, false, "callback", "operation.vehicle.send_to_depot", "vehicle-owner", "authored-vehicle-economy", "depot-target-equal,sell-on-arrival-equal"},
    {12, "SellVehicle", "visitor", true, true, false, "callback", "operation.vehicle.sell_batch", "every-vehicle-owner", "authoritative-resale", "vehicles-absent,balance-delta-equal"},
    {13, "BuyVehicle", "visitor-plus-stock-gui", true, true, false, "entity-callback", "operation.vehicle.buy", "depot-owner", "authoritative-purchase", "vehicle-exists,consist-equal,owner-equal,balance-delta-equal"},
    {14, "ReplaceVehicle", "visitor-plus-stock-gui", true, true, false, "entity-callback", "operation.vehicle.replace", "vehicle-owner", "authoritative-purchase-and-resale", "consist-equal,owner-equal,balance-delta-equal"},
    {15, "BuildProposal", "make_cmd::BuildProposal+CommandList::Add+visitor", true, true, false, "proposal-callback", "proposal_runtime.apply", "proposal-access-policy", "authoritative-quoted-cost", "geometry-fingerprint-equal,construction-fingerprint-equal,ownership-equal,balance-delta-equal"},
    {16, "RemoveField", "visitor", true, true, false, "none", "unsupported", "host-autonomy", "none", "field-absence-equal"},
    {17, "CreateTowns", "visitor", true, true, false, "entity-callback", "unsupported", "host-world-authority", "none", "town-set-equal"},
    {18, "RemoveTown", "visitor", true, true, false, "callback", "unsupported", "host-world-authority", "none", "town-absent"},
    {19, "DevelopTown", "visitor", true, true, false, "none", "town_development_runtime.apply", "host-town-model", "none", "town-capacities-equal,structural-fingerprint-equal"},
    {20, "SetTownInfo", "visitor", true, true, false, "none", "town_development_runtime.set_info", "host-town-model", "none", "town-info-equal"},
    {21, "InstantlyUpdateTownCargoNeeds", "visitor", true, true, false, "none", "unsupported", "host-town-model", "none", "town-cargo-needs-equal"},
    {22, "ConnectTownsAndIndustries", "visitor", true, true, false, "none", "unsupported", "host-world-authority", "none", "connection-graph-equal"},
    {23, "SetSimBuildingManualDevelopment", "visitor", true, true, false, "none", "agent_policy_runtime.apply", "host-agent-policy", "none", "manual-development-flag-equal"},
    {24, "SetSimBuildingClosureTimeStamp", "visitor", true, true, false, "none", "unsupported", "host-agent-policy", "none", "closure-timestamp-equal"},
    {25, "ReplaceTerrain", "visitor", true, true, false, "callback", "unsupported", "proposal-access-policy", "authoritative-quoted-cost", "terrain-fingerprint-equal,balance-delta-equal"},
    {26, "SetDate", "visitor", true, true, false, "none", "calendar_runtime.set_date", "host-calendar", "none", "date-equal,vehicle-availability-equal"},
    {27, "SaveGame", "command-list-observer", false, false, false, "callback", "recovery.anchor_save", "local-recovery-only", "none", "boundary-receipt-bound"},
    {28, "SetColor", "visitor-after-local-apply", true, false, true, "callback", "operation.entity.color", "entity-owner", "none", "color-equal"},
    {29, "SetName", "visitor-after-local-apply", true, false, true, "callback", "operation.entity.name", "entity-owner", "none", "name-equal"},
    {30, "SetVehicleManualDeparture", "visitor", true, true, false, "callback", "operation.vehicle.manual_departure", "vehicle-owner", "none", "manual-departure-equal"},
    {31, "Book", "command-list-observer", false, false, false, "none", "authored_finance_runtime.neutralize", "authoritative-economy", "native-ledger-neutralized", "authored-balance-equal"},
    {32, "SendScriptEvent", "native-send-command-wrapper", false, false, false, "script-result", "protocol.action_dispatch", "protocol-handler", "action-defined", "canonical-digest-equal"},
    {33, "SetNoCosts", "visitor", true, true, false, "none", "unsupported", "match-configuration", "none", "no-costs-flag-equal"},
    {34, "SetAnimalState", "command-list-observer", false, false, false, "none", "cosmetic-autonomy", "native-cosmetic", "none", ""},
    {35, "SpawnAnimal", "command-list-observer", false, false, false, "entity-callback", "cosmetic-autonomy", "native-cosmetic", "none", ""},
    {36, "Debug_SetSimPersonState", "visitor", true, true, false, "none", "agent_presentation_runtime.apply", "host-agent-policy", "none", "presented-agent-state-bounded"},
}};

template <std::size_t Tag>
inline constexpr const CommandSafetyPolicy& CommandSafetyPolicyFor() {
  static_assert(Tag < kCommandSafetyRegistry.size());
  static_assert(kCommandSafetyRegistry[Tag].tag == Tag);
  return kCommandSafetyRegistry[Tag];
}

}  // namespace tpf2mp::native_command
